version: "3"
services:
    nextjs-app:
        build:
            dockerfile: ./dockerfile.yaml
            context: .
        ports:
            - "3000:3000"
        container_name: devpass-fe
        env_file:
            - .env
        restart: always
