FROM node:21.4.0-alpine

# 디렉토리 지정
WORKDIR /usr/src/app

# 환경변수
ENV NEXT_PUBLIC_NEST_APP_ENDPOINT="http://192.168.1.80:9090"
ENV NEXT_PUBLIC_HASURA_ENDPOINT="http://192.168.1.80:8080/v1/graphql"
ENV NEXT_PUBLIC_TINY_MCE_API_KEY="gp6cj75qlegr0u0l30y7usxg1uk4uid11q8ghuqmv1qvhzaf"

# 의존성 설치를 위해 package.json, yarn.lock 복사
COPY package.json ./
COPY yarn.lock ./

# 의존성 설치
RUN yarn

# 필요한 모든 파일을 복사
COPY . .

# next.js 앱 빌드
RUN yarn build

# 컨테이너 포트
EXPOSE 3000

# 애플리케이션 실행
CMD [ "yarn", "start" ]