export enum EstimateDetailsOptionTypeEnum {
    LICENSE_PROJECT_NAME = "license_project_name",
    YEAR = "year",
    TYPE = "type",
    PURPOSE = "purpose",
    CLASS = "class",
    PRODUCT_TYPE = "product_type",
    PRODUCT = "product",
    DETAILS = "details",
    UNIT = "unit",
    AMOUNT = "amount",
    PRICE = "price",
    STANDARD_PRICE = "standard_price",
    SUPPLY_PRICE = "supply_price",
    MONTHLY_REPAIR_PRICE = "monthly_repair_price",
    TOTAL_REPAIR_PRICE = "total_repair_price",
    START_DATE = "start_date",
    END_DATE = "end_date",
    LICENSE_CONTRACT_ID = "license_contract_id",
    NOTE = "note",
}
